server:
  port: 9991

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  datasource:
    url: jdbc:mysql://staging-rzidentity.cx1lnhz9gmnb.us-east-2.rds.amazonaws.com:3306/dev_nab
    username: admin
    password: 9POUk34d1JqC36Aq
    driver-class-name: com.mysql.cj.jdbc.Driver
